// Ride page strings (Hebrew, right-to-left). Piste and lift names stay as in OpenStreetMap.
export const t = {
  title: 'פאס דה לה קאסה',
  subtitle: 'גראנדווליירה, אנדורה · שטח אמיתי',
  loading: 'טוענים את ההר…',
  loadingPct: (p) => `מורידים את ההר ${p}%…`,
  preparing: 'מכינים את המסלולים…',
  loadFailed: 'לא הצלחנו לטעון את ההר',
  start: 'יאללה לגלוש 🏂',
  speed: 'קמ״ש',
  sec: 'שנ׳',
  altitude: 'מ׳',
  airtime: (s) => `אוויר ${s.toFixed(1)} שנ׳ ✈️`,
  crashed: 'אאוץ׳! נפילה 💥',
  backToApp: '→ חזרה לאפליקציה',
  controlsTitle: 'שליטה',
  controls: [
    ['← →  /  A D', 'פנייה (קאנט)'],
    ['↑  /  W', 'כיווץ למהירות · דחיפה במישור'],
    ['↓  /  S', 'בלימה'],
    ['רווח', 'החזיקו לטעינה, שחררו לקפיצה'],
    ['R', 'חזרה להתחלה (או התחלת הריצה מחדש)'],
    ['C', 'מצלמה: מאחור / עיני הרוכב'],
    ['M / Esc', 'תפריט: רכבלים וריצות על זמן'],
  ],
  credits: 'גובה: AWS Terrain Tiles · מפה: © OpenStreetMap contributors',
  menuTitle: 'לאן עולים?',
  free: 'גלישה חופשית',
  timed: 'ריצה על זמן',
  liftTop: 'ראש הרכבל',
  kinds: { chair: 'כיסאות', cabin: 'גונדולה', drag: 'גרירה' },
  difficulty: { novice: 'ירוקה', easy: 'כחולה', intermediate: 'אדומה', advanced: 'שחורה', expert: 'שחורה', freeride: 'פרירייד', '': '' },
  meters: (m) => `${Math.round(m).toLocaleString('he-IL')} מ׳`,
  drop: (m) => `↓ ${Math.round(m)} מ׳`,
  best: 'שיא',
  noBest: 'אין שיא',
  resume: 'המשך לגלוש',
  menu: 'תפריט',
  gate: (n, total) => `שער ${n}/${total}`,
  go: 'יאללה! ⏱️',
  missed: (n) => `פספסת ${n === 1 ? 'שער' : `${n} שערים`} · +${n * 5} שנ׳`,
  finish: 'סיום! 🏁',
  newBest: 'שיא חדש! 🏆',
  toStart: 'גלשו דרך שער ההתחלה',
  offPiste: 'מחוץ למסלול',
  menuKeys: 'M / Esc · תפריט',
  touchHint: 'גררו כאן: הצידה לפנייה, למעלה לכיווץ, למטה לבלימה',
  touchHint2: 'החזיקו שמאל / ימין לפנייה · החליקו למעלה לקפיצה · למטה לבלימה',
  touchJump: 'קפיצה',
  touchBrake: 'בלימה',
  touchTilt: 'הטיה 📱',
  touchControls: [
    ['👈 👉', 'החזיקו את צד שמאל או ימין של המסך כדי לפנות; שחררו כדי להתיישר'],
    ['☝️ החלקה למעלה', 'קפיצה (החזקה לפני ההחלקה = קפיצה גבוהה)'],
    ['👇 החלקה למטה', 'בלימה, כל עוד האצבע למטה'],
    ['✌️ שתי אצבעות', 'כיווץ למהירות'],
    ['⚙️', 'הגדרות: הטיה, ג׳ויסטיק, סיוע בהיגוי'],
  ],
  sound: 'צליל',
  boardercross: 'בורדרקרוס',
  // Popular runs & medals
  popular: 'המסלולים הפופולריים',
  stars: (n) => `⭐ ${n}`,
  locked: (n) => `🔒 צריך ${n} ⭐`,
  target: 'זמן זהב',
  computing: 'מחשבים זמני יעד…',
  medals: { gold: 'זהב', silver: 'כסף', bronze: 'ארד' },
  medalIcon: { gold: '🥇', silver: '🥈', bronze: '🥉' },
  noMedal: 'בלי מדליה הפעם',
  ghostMine: 'הגוסט שלך',
  ghostGold: 'רוכב הזהב',
  vsGhost: (d) => `${d > 0 ? '+' : '−'}${Math.abs(d).toFixed(2)}`,
  finishTitle: 'סיום!',
  yourTime: 'הזמן שלך',
  topSpeed: 'מהירות שיא',
  air: 'זמן באוויר',
  missedGates: 'שערים שפוספסו',
  retry: 'שוב 🔁',
  nextRun: 'למסלול הבא ←',
  toMenu: 'לתפריט',
  starsEarned: (n) => `+${n} ⭐`,
  unlockedNew: 'נפתחו מסלולים חדשים! 🔓',
  freeStart: (lift) => `מראש ${lift}`,
  // Settings
  settings: 'הגדרות',
  controlMode: 'שליטה בטלפון',
  modes: { sides: 'החזקת צדדים', tilt: 'הטיית הטלפון', stick: 'ג׳ויסטיק' },
  assist: 'סיוע בהיגוי',
  assistHint: 'מיישר את הקרש לכיוון התנועה ומונע החלקות מפתיעות',
  fullscreen: 'מסך מלא',
  close: 'סגירה',
};
