// Ride page strings (Hebrew, right-to-left). Piste and lift names stay as in OpenStreetMap.
export const t = {
  title: 'פאס דה לה קאסה',
  subtitle: 'גראנדווליירה, אנדורה · שטח אמיתי',
  loading: 'טוענים את ההר…',
  loadFailed: 'לא הצלחנו לטעון את ההר',
  start: 'יאללה לגלוש 🏂',
  speed: 'קמ״ש',
  altitude: 'מ׳',
  airtime: (s) => `אוויר ${s.toFixed(1)} שנ׳ ✈️`,
  crashed: 'אאוץ׳! נפילה 💥',
  backToApp: '→ חזרה לאפליקציה',
  controlsTitle: 'שליטה',
  controls: [
    ['← →  /  A D', 'פנייה (קאנט)'],
    ['↑  /  W', 'כיווץ למהירות · דחיפה במישור'],
    ['↓  /  S', 'בלימה'],
    ['רווח', 'החזיקו לטעינה, שחררו לקפיצה'],
    ['R', 'חזרה להתחלה (או התחלת הריצה מחדש)'],
    ['C', 'מצלמה: מאחור / עיני הרוכב'],
    ['M / Esc', 'תפריט: רכבלים וריצות על זמן'],
  ],
  credits: 'גובה: AWS Terrain Tiles · מפה: © OpenStreetMap contributors',
  menuTitle: 'לאן עולים?',
  free: 'גלישה חופשית',
  timed: 'ריצה על זמן',
  liftTop: 'ראש הרכבל',
  kinds: { chair: 'כיסאות', cabin: 'גונדולה', drag: 'גרירה' },
  difficulty: { novice: 'ירוקה', easy: 'כחולה', intermediate: 'אדומה', advanced: 'שחורה', expert: 'שחורה', freeride: 'פרירייד', '': '' },
  meters: (m) => `${Math.round(m).toLocaleString('he-IL')} מ׳`,
  drop: (m) => `↓ ${Math.round(m)} מ׳`,
  best: 'שיא',
  noBest: 'אין שיא',
  resume: 'המשך לגלוש',
  menu: 'תפריט',
  gate: (n, total) => `שער ${n}/${total}`,
  go: 'יאללה! ⏱️',
  missed: (n) => `פספסת ${n === 1 ? 'שער' : `${n} שערים`} · +${n * 5} שנ׳`,
  finish: 'סיום! 🏁',
  newBest: 'שיא חדש! 🏆',
  toStart: 'גלשו דרך שער ההתחלה',
  offPiste: 'מחוץ למסלול',
  menuKeys: 'M / Esc · תפריט',
  touchHint: 'גררו כאן: הצידה לפנייה, למעלה לכיווץ, למטה לבלימה',
  touchJump: 'קפיצה',
  touchBrake: 'בלימה',
  touchTilt: 'הטיה 📱',
  touchControls: [
    ['👈 צד שמאל', 'גררו הצידה לפנייה, למעלה לכיווץ, למטה לבלימה'],
    ['קפיצה', 'החזיקו לטעינה, שחררו לקפיצה'],
    ['הטיה 📱', 'היגוי בהטיית הטלפון'],
    ['☰', 'תפריט: רכבלים וריצות על זמן'],
  ],
  sound: 'צליל',
};
